services:
  teapprendo-platform:
    image: teapprendo-platform:1.0.0-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod